#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: запуск media.tatarverse.cc на люди.
# Воркер tally-intake и вебхук Tally уже настроены - этих стадий здесь нет.
# Аналитика намеренно остается выключенной: privacy.md обещает, что ее нет.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# Корень репозитория ищем от самого скрипта, чтобы визард работал и из
# scripts/, и из корня. Значения запоминаются между прогонами в
# .wizard-launch.env, а боевое место для них - main.config.ts.
_here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
for _candidate in "$_here" "$_here/.." "$PWD"; do
  if [[ -f "$_candidate/main.config.ts" ]]; then
    REPO_ROOT="$(cd "$_candidate" && pwd)"
    break
  fi
done
if [[ -z "${REPO_ROOT:-}" ]]; then
  printf '  %s✗ main.config.ts не найден - запускайте визард из репозитория.%s\n' "$RED" "$RESET"
  exit 1
fi
CONFIG="$REPO_ROOT/main.config.ts"
ENV_FILE="$REPO_ROOT/.wizard-launch.env"
SITE_URL="https://media.tatarverse.cc/"

# config_set_verification NAME VALUE - вписывает код подтверждения в
# массив `verifications` в main.config.ts. Идемпотентно: правит строку с
# нужным `name`, а не дописывает новую.
config_set_verification() {
  local name="$1" value="$2"
  if [[ -z "$value" ]]; then
    note "пусто - $name пропускаю"
    return 0
  fi
  python3 - "$CONFIG" "$name" "$value" <<'PY'
import io, re, sys
path, name, value = sys.argv[1], sys.argv[2], sys.argv[3]
s = io.open(path, encoding="utf-8").read()
pattern = re.compile(r'(\{ name: "' + re.escape(name) + r'", content: ")[^"]*(" \},)')
if not pattern.search(s):
    sys.exit("в main.config.ts нет строки verifications для " + name)
io.open(path, "w", encoding="utf-8").write(pattern.sub(lambda m: m.group(1) + value + m.group(2), s))
PY
  printf '  %s✓ записал%s %s → main.config.ts\n' "$GREEN" "$RESET" "$name"
}

# config_enable_indexnow KEY - переводит indexNow в { enabled: true, key }.
config_enable_indexnow() {
  local key="$1"
  python3 - "$CONFIG" "$key" <<'PY'
import io, re, sys
path, key = sys.argv[1], sys.argv[2]
if not re.fullmatch(r"[A-Za-z0-9-]{8,128}", key):
    sys.exit("ключ IndexNow должен быть 8-128 символов [A-Za-z0-9-], получено: " + repr(key))
s = io.open(path, encoding="utf-8").read()
pattern = re.compile(r"indexNow: \{[^}]*\},")
if not pattern.search(s):
    sys.exit("в main.config.ts не найдена строка indexNow")
s = pattern.sub('indexNow: { enabled: true, key: "' + key + '" },', s, count=1)
io.open(path, "w", encoding="utf-8").write(s)
PY
  printf '  %s✓ включил%s IndexNow → main.config.ts\n' "$GREEN" "$RESET"
}

banner "media.tatarverse.cc - выход на люди"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare Pages: проект"
say "Статику собирает Astro в dist/. Подключаем репозиторий к Pages."
open_url "https://dash.cloudflare.com/?to=/:account/pages/new/provider/github"
step "Connect to Git → выберите репозиторий proxima812/media.tatarverse.cc."
step "Production branch: main"
step "Framework preset: Astro (или None - важны две строки ниже)."
step "Build command:        bun run build"
step "Build output directory: dist"
note "Переменные окружения сборке не нужны: конфигурация лежит в main.config.ts."
step "Save and Deploy - дождитесь, пока первая сборка станет зеленой."
ask PAGES_PROJECT "Как назвали проект в Pages (например media-tatarverse-cc):"
write_env PAGES_PROJECT "$PAGES_PROJECT"
pause "Сборка прошла и сайт открывается на *.pages.dev?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Домен media.tatarverse.cc"
say "site.url в main.config.ts уже прописан как $SITE_URL - домен обязан"
say "совпадать, иначе canonical, sitemap и hreflang будут врать."
open_url "https://dash.cloudflare.com/?to=/:account/pages/view/$PAGES_PROJECT/domains"
step "Custom domains → Set up a custom domain → media.tatarverse.cc"
step "Если домен уже в этом аккаунте Cloudflare - запись CNAME создастся сама."
step "Если домен у другого регистратора - перенесите NS на Cloudflare либо"
step "  добавьте CNAME media.tatarverse.cc → <проект>.pages.dev вручную."
note "Выпуск сертификата занимает от минуты до получаса."
pause "https://media.tatarverse.cc/ открывается по HTTPS?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Google Search Console: код"
say "Сейчас только забираем код. Подтверждать будем на стадии 8, когда тег"
say "уже уедет на живой сайт - раньше Google его не увидит."
open_url "https://search.google.com/search-console/welcome"
step "Выберите тип ресурса «Ресурс с префиксом URL» и введите $SITE_URL"
step "В способах подтверждения раскройте «Тег HTML»."
step "Из <meta name=\"google-site-verification\" content=\"...\"> скопируйте"
step "  только значение content, без кавычек и без самого тега."
warn "Окно подтверждения не закрывайте - вернемся к нему на стадии 8."
ask GOOGLE_SITE_VERIFICATION "Вставьте content для google-site-verification:"
write_env GOOGLE_SITE_VERIFICATION "$GOOGLE_SITE_VERIFICATION"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Яндекс Вебмастер: код"
open_url "https://webmaster.yandex.ru/sites/add/"
step "Добавьте сайт media.tatarverse.cc"
step "Способ подтверждения → «Мета-тег»."
step "Из <meta name=\"yandex-verification\" content=\"...\"> скопируйте content."
ask YANDEX_VERIFICATION "Вставьте content для yandex-verification:"
write_env YANDEX_VERIFICATION "$YANDEX_VERIFICATION"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Bing Webmaster: код"
say "Bing нужен не только сам по себе: IndexNow с ним связан."
open_url "https://www.bing.com/webmasters/home"
step "Add a site → media.tatarverse.cc"
step "Способ подтверждения → «HTML Meta Tag»."
step "Из <meta name=\"msvalidate.01\" content=\"...\"> скопируйте content."
ask MSVALIDATE "Вставьте content для msvalidate.01:"
write_env MSVALIDATE "$MSVALIDATE"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "IndexNow: ключ"
say "Ключ пингует поисковики при обновлении карточек. Файл /<ключ>.txt"
say "стартер отдает сам - руками его создавать не нужно."
open_url "https://www.bing.com/indexnow/getstarted"
step "Нажмите «Generate» и скопируйте ключ."
note "Требование стартера: 8-128 символов, только [A-Za-z0-9-]."
ask INDEXNOW_KEY "Вставьте ключ IndexNow (Enter - пропустить):"
if [[ -n "$INDEXNOW_KEY" ]]; then
  write_env INDEXNOW_KEY "$INDEXNOW_KEY"
else
  SKIPPED+=("IndexNow: ключ не задан, indexNow остался enabled: false")
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Записать в main.config.ts, проверить и выкатить"
say "Все собранные значения уезжают в main.config.ts, потом verify и пуш."
config_set_verification "google-site-verification" "$GOOGLE_SITE_VERIFICATION"
config_set_verification "yandex-verification" "$YANDEX_VERIFICATION"
config_set_verification "msvalidate.01" "$MSVALIDATE"
[[ -n "$INDEXNOW_KEY" ]] && config_enable_indexnow "$INDEXNOW_KEY"
printf '\n'
say "Запускаю bun run verify - это сборка 681 страницы, около минуты."
if ! (cd "$REPO_ROOT" && bun run verify); then
  warn "verify красный. Правки в main.config.ts на месте - почините и"
  warn "перезапустите визард: собранные значения уже сохранены."
  exit 1
fi
printf '\n'
say "Проверяю, что теги реально попали в собранный HTML:"
(cd "$REPO_ROOT" && grep -o '<meta name="[a-z0-9.-]*verification[^>]*>' dist/index.html || true)
(cd "$REPO_ROOT" && grep -o '<meta name="msvalidate.01"[^>]*>' dist/index.html || true)
if [[ -n "$INDEXNOW_KEY" ]]; then
  if [[ -f "$REPO_ROOT/dist/$INDEXNOW_KEY.txt" ]]; then
    printf '  %s✓%s dist/%s.txt на месте\n' "$GREEN" "$RESET" "$INDEXNOW_KEY"
  else
    warn "dist/$INDEXNOW_KEY.txt не найден - проверьте indexNow в main.config.ts"
  fi
fi
printf '\n'
if confirm "Закоммитить main.config.ts и запушить в main?"; then
  (cd "$REPO_ROOT" && git add main.config.ts && \
    git commit -q -m "chore: коды подтверждения владения доменом и ключ IndexNow" && \
    git push origin main)
  say "Запушено. Cloudflare Pages подхватит коммит и пересоберет сайт."
else
  SKIPPED+=("коммит и пуш main.config.ts - сделайте вручную, иначе теги не уедут на сайт")
fi
pause "Дождитесь зеленого деплоя в Cloudflare Pages, потом Enter."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Подтвердить владение в трех консолях"
say "Теги теперь на живом сайте. Проверим и нажмем «Подтвердить»."
say "Сначала убедимся, что теги действительно отдаются с продакшена:"
if command -v curl >/dev/null 2>&1; then
  curl -s "$SITE_URL" | grep -o '<meta name="[^"]*verification[^>]*>' || \
    warn "теги на живом сайте не видны - возможно, деплой еще не закончился"
  curl -s "$SITE_URL" | grep -o '<meta name="msvalidate.01"[^>]*>' || true
else
  note "curl не найден - проверьте теги в исходном коде страницы вручную."
fi
printf '\n'
step "Google: вернитесь в открытое окно Search Console → «Подтвердить»."
open_url "https://search.google.com/search-console"
pause "Google подтвердил?"
step "Яндекс: Вебмастер → «Проверить»."
open_url "https://webmaster.yandex.ru/sites/"
pause "Яндекс подтвердил?"
step "Bing: Webmaster Tools → «Verify»."
open_url "https://www.bing.com/webmasters/home"
pause "Bing подтвердил?"
printf '\n'
say "Отправьте карту сайта в каждой консоли: ${SITE_URL}sitemap-index.xml"
pause "Готово?"

finish
